conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('admin/', admin.site.urls),
      path('', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users import views

app_name = 'users'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index_page'),
    path('create-users/', views.create_users),
    path('write-users-to-file/', views.write_users_to_file),
    path('users-salary-report-to-file/', views.users_salary_report_to_file, name='users_salary_report_to_file'),
    path('send-report-file-with-email/', views.send_report_file_with_email, name='send_report_file_with_email'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    person_id = models.BigIntegerField(null=True,
                                       validators=[MinValueValidator(10000000000000),
                                                   MaxValueValidator(99999999999999)])
    gender = models.IntegerField(choices=GENDER_CHOICES, null=True, )
    salary = models.DecimalField(decimal_places=2, max_digits=9, null=True, )
    birthday = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.email

users/views.py
from django.contrib import messages
from django.http import HttpResponse, FileResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy

from users.models import CustomUser
from . import utilities
from .services import UserService
from django.utils.timezone import localtime


def create_users(request):
    datas = utilities.users_data_parse_from_excel(file_name='users.xlsx')
    users = CustomUser.objects.bulk_create([CustomUser(email=data['email'],
                                                       last_name=data['last_name'],
                                                       first_name=data['first_name'],
                                                       person_id=data['person_id'],
                                                       gender=data['gender'],
                                                       salary=data['salary'],
                                                       birthday=data['birthday']) for data in datas])

    return HttpResponse(f"{len(users)} objects created!")


def write_users_to_file(request):
    users_data = UserService.get_users_list(
        fields=['id', 'person_id', 'email', 'last_name', 'first_name', 'salary', 'birthday'])
    utilities.write_users_data_to_excel(file_name='new_users.xlsx', sheet_name='users_data', users_data=users_data)
    return HttpResponse(f"{len(users_data)} objects were written to a file!")


def users_salary_report_to_file(request):
    users = UserService.get_users_list(fields=['email', 'last_name', 'first_name', 'salary'], count=7)
    file = utilities.users_salary_report_build(users=users)
    file_name = 'users_salary_report_' + localtime().strftime('%d-%m-%Y_%H-%M-%S') + '.xlsx'
    return FileResponse(
        file,
        as_attachment=True,
        filename=file_name,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )


def send_report_file_with_email(request):
    users = UserService.get_users_list(fields=['email', 'last_name', 'first_name', 'salary'], count=7)
    file = utilities.users_salary_report_file_build_for_email_send(users=users)
    superusers = UserService.get_superusers_list()
    server = utilities.SmtpServer(recipients=superusers, file=file)
    server.send()
    return redirect(reverse_lazy('users:index_page'))

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="Yakubov Developer"/>
    <meta name="author" content="Sirojiddin Yakubov"/>
    <title>Yakubov Developer - IT va Dasturlash</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
          rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#page-top">Yakubov Developer</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    </div>
</nav>
<!-- Masthead-->
<header class="masthead">
    <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-white font-weight-bold">Yakubov Developer - IT va Dasturlash</h1>
                <hr class="divider"/>
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-8 align-self-baseline">
                {#                        <p class="text-white-75 mb-5">Foydalanuvchilar haqida excel faylda hisobot olish</p>#}
                <p class="text-white-75 mb-5">Foydalanuvchilar haqida excel faylda hisobot jo'natish</p>
                {#                        <a class="btn btn-primary btn-xl" href="{% url 'users:users_salary_report_to_file' %}">Hisobot olish</a>#}
                <a class="btn btn-primary btn-xl" href="{% url 'users:send_report_file_with_email' %}">Email orqali
                    hisobot jo'natish</a>
            </div>
        </div>
    </div>
</header>
</body>
</html>